### ISSUE TITLE
Make it possible to add environment variables and labels as part of module.yaml

### ISSUE THREAD

**Issue by goldmann** [containers-tools/cct#81]
It would be a nice feature if we would be able to add to image env variables and labels that are defined in `module.yaml`.

Low priority.

**Comment by rwngwn** [comment]
this is very nice feature - and will be pretty neat to do.
It will be much more easy to do with a buildah.

**Comment by goldmann** [comment]
I would probably raise priority of this issue, for me this looks like an important thing to maintain units of changes (modules).

**Comment by rwngwn** [comment]
lets talk about this when we split repos and start using CCT.

**Comment by rcernich** [comment]
Why don't we broaden the whole idea such that image.yaml is an extension of module.yaml that adds image specific details, mainly FROM.  At that point, the module system is really just merging a set of files to create what was our old image.yaml format.  This would make image.yaml look something like:

```yaml
name: "jboss-eap-6/eap64-openshift
description: "..."
version: "..."
from: "jboss-eap-6/eap64:latest"
labels: [...]
envs: [...]
requires:
  - name: "core.jolokia"
    url: https://github.com/jboss-openshift/modules-core.git
    path: jolokia
...
```

Adding in "overrides," one could specify a property like: module.core.jolokia.url=/home/me/src/modules-core.  (I'll add this and more to jboss-dockerfiles/dogen#12.)  It would also be great if version could be specified during the build or from the tag/ref specified.
